// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALgcvxO69XH_x8KH-jMtfLI6TcLpxnJRE',
    appId: '1:969712173682:web:69db5bdad42fc8a42478eb',
    messagingSenderId: '969712173682',
    projectId: 'estiloexatozap-59075',
    authDomain: 'estiloexatozap-59075.firebaseapp.com',
    storageBucket: 'estiloexatozap-59075.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOAZnfFrKpvghos926IyywwnWNlBkYHYk',
    appId: '1:969712173682:android:18c70670f04e3d792478eb',
    messagingSenderId: '969712173682',
    projectId: 'estiloexatozap-59075',
    storageBucket: 'estiloexatozap-59075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHzqz-3u-n0y6LmfqZYCybWDm79YCiQMU',
    appId: '1:969712173682:ios:1f122655c36d262c2478eb',
    messagingSenderId: '969712173682',
    projectId: 'estiloexatozap-59075',
    storageBucket: 'estiloexatozap-59075.firebasestorage.app',
    iosBundleId: 'com.example.estiloExatoZap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHzqz-3u-n0y6LmfqZYCybWDm79YCiQMU',
    appId: '1:969712173682:ios:1f122655c36d262c2478eb',
    messagingSenderId: '969712173682',
    projectId: 'estiloexatozap-59075',
    storageBucket: 'estiloexatozap-59075.firebasestorage.app',
    iosBundleId: 'com.example.estiloExatoZap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALgcvxO69XH_x8KH-jMtfLI6TcLpxnJRE',
    appId: '1:969712173682:web:8e838a4f5c8399f42478eb',
    messagingSenderId: '969712173682',
    projectId: 'estiloexatozap-59075',
    authDomain: 'estiloexatozap-59075.firebaseapp.com',
    storageBucket: 'estiloexatozap-59075.firebasestorage.app',
  );
}
